eTicket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from ticketApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name = 'index'),
    path('organizationDetails/', views.organizationDetails, name = 'organizationDetails'),
    path('billingAddress/', views.billingAddress, name = 'billingAddress'),
    path('paymentMethods/', views.paymentMethods, name = 'paymentMethods'),
    path('changePassword/', views.changePassword, name = 'changePassword'),
    path('ticketGenerator/', include('ticketGenerator.urls')),

    

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ticketGenerator/urls.py
# Welcome Commander...

from django.urls import path, include
from . import views

app_name = 'ticketGenerator'

urlpatterns = [
   path('', views.disputeTicket, name = 'disputeTicket'),
   path('generateNewTicket/', views.generateNewTicket, name = 'generateNewTicket'),
   path('todayOffer/', views.todayOffer, name = 'todayOffer'),
]

ticketGenerator/models.py
from django.db import models

# Create your models here.

ticketApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'ticketApp/index.html')
	
	
def organizationDetails(request):
	return render(request, 'ticketApp/organizationDetails.html')

	
def billingAddress(request):
	return render(request, 'ticketApp/billingAddress.html')

	
def paymentMethods(request):
	return render(request, 'ticketApp/paymentMethods.html')
	
	
def changePassword(request):
	return render(request, 'ticketApp/changePassword.html')
	

ticketGenerator/views.py
from django.shortcuts import render

# Create your views here.

def disputeTicket(request):
	return render(request, 'ticketGenerator/disputeTicket.html')
	
	
	
def generateNewTicket(request):
	return render(request, 'ticketGenerator/generateNewTicket.html')
	
	
def todayOffer(request):
	return render(request, 'ticketGenerator/todayOffer.html')	

ticketApp/templates/ticketApp/basic.html
<!-- Welcome Commander What's New on your Creative Mind' -->
{% load static %}
<!doctype html>

<html lang="en">
<head>
	<meta charset="utf-8">

	<meta name="description" content="The HTML5 Herald">
	<meta name="author" content="SitePoint">

	<link rel="stylesheet" href="{% static 'ticketApp/CSS/style.css'%}">
	<link rel="stylesheet" href="{% static 'ticketApp/CSS/bootstrap.css'%}">
	<script src="{% static 'ticketApp/JS/script.js'%}"></script>
	   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
<!--	<script src="{% static 'ticketApp/JS/jquery.js'%}"></script>-->
<!--	<script src="{% static 'ticketApp/JS/bootstrap.js'%}"></script>-->
	<link rel = "icon" href = "{% static 'ticketApp/IMAGES/logo.png'%}" type = "image/x-icon">

</head>
<body>

<body>

<header>
  <nav>
    <div class="logo">
      <img class = "img1" src="{% static 'ticketApp/IMAGES/logo.png'%}" alt="">
    </div>
    <ul>
      <li><a href="#">E-Booking</a></li>
      <li><a href="#">About us</a></li>
      <li><a href="#">Services</a></li>
      <li><a href="#">Contact Us </a></li>
      <li><a href="#">Reviews</a></li>
      <li><a href="{% url 'index' %}">My Account</a></li>
      <li><a href="#">Join Us</a></li>
    </ul>
  </nav>
  <div class="user-detail">
    <ul>
      <li><a href="#" class="login-back">log in</a></li>
      <li><a href="#">sing Up</a></li>
    </ul>
    
  </div>



<div class="social-media-icone">
  <ul>
    <li><a href="#"><span><img src="{% static 'ticketApp/IMAGES/google-icone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketApp/IMAGES/inp-licone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketApp/IMAGES/inst-icone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketApp/IMAGES/facebook-icone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketApp/IMAGES/tiwwe-icone.png'%}" alt=""></span></a></li>
  </ul>
  

  
</div>
	
	</header>
	
	{% block content %} {% endblock %}
</body>
</html>

ticketApp/templates/ticketApp/billingAddress.html
{% extends 'ticketApp/basic.html' %}
	{% block content %} 
	{% load static %}
	
<div class = "backImage">
	<div class = "childBox">

		<div class = "cartoonPic">
			<img class = "img1" src="{% static 'ticketApp/IMAGES/cartoonPic.png'%}" alt="">
		</div>
		<div class = "socialSites">
		<ul>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/inst-icone.png'%}" alt="">instagram@insta.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/facebook-icone.png'%}" alt="">facebook@facebook.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/tiwwe-icone.png'%}" alt="">twiter@twitter.com</span></a></li>
		</ul>  
		</div>
		<div class = "linePosition">
<hr class="new4">
<div class = "dotPositionFull"><span class="dot"></span><br><p class = "h4Color">Personal details</p></div>
<div class = "dotPosition1"><span class="dot"></span><br><p class = "h4Color">Organization details</p></div>
<div class = "dotPosition2"><span class="dot"></span><br><p class = "h4Color">Billing address</p></div>
<div class = "dotPosition3"><span class="dot1"></span><br><p class = "h4Color">Payment method</p></div>
<div class = "dotPosition4"><span class="dot1"></span><br><p class = "h4Color">Change password</p></div>
</div>
		<div class = "personalDetailColor"><h3><b>Billing Address</h3></div>
		
		

	<form action = "{% url 'paymentMethods' %}" method = "GET">
	<div class = "billingLocation">
		 <input id = "billingShape" type="text" id="fname" name="fname" placeholder="Your Country"><br>
		  <input id = "billingShape" type="text" id="fname" name="fname" placeholder="Pincode/ Zipcode"><br>
		 <input id = "billingShape" type="text" id="fname" name="fname" placeholder="Address LIne 1"><br>
		  <input id = "billingShape" type="text" id="fname" name="fname" placeholder="Address Line 2"><br>
		   <input id = "billingShape" type="text" id="fname" name="fname" placeholder="Street"><br></div>
				<div class = "submitButtons3">
			<button type="button" class="btnLast">Edit</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<button type="submit" class= "btnLast">Save</button>
	</form>	
		
	</div>
</div>
	
	
		{% endblock %}

ticketApp/templates/ticketApp/changePassword.html
{% extends 'ticketApp/basic.html' %}
	{% block content %} 
	{% load static %}
	
<div class = "backImage">
	<div class = "childBox">

		<div class = "cartoonPic">
			<img class = "img1" src="{% static 'ticketApp/IMAGES/cartoonPic.png'%}" alt="">
		</div>
		<div class = "socialSites">
		<ul>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/inst-icone.png'%}" alt="">instagram@insta.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/facebook-icone.png'%}" alt="">facebook@facebook.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/tiwwe-icone.png'%}" alt="">twiter@twitter.com</span></a></li>
		</ul>  
		</div>
		
		<div class = "linePosition">
<hr class="new4">
<div class = "dotPositionFull"><span class="dot"></span><br><p class = "h4Color">Personal details</p></div>
<div class = "dotPosition1"><span class="dot"></span><br><p class = "h4Color">Organization details</p></div>
<div class = "dotPosition2"><span class="dot"></span><br><p class = "h4Color">Billing address</p></div>
<div class = "dotPosition3"><span class="dot"></span><br><p class = "h4Color">Payment method</p></div>
<div class = "dotPosition4"><span class="dot"></span><br><p class = "h4Color">Change password</p></div>
</div>
		
		<div class = "personalDetailColor"><h3><b>Change Password</h3></div>
		
		

	<form action = "{% url 'ticketGenerator:disputeTicket' %}" method = "GET">
		<div class = "changePasswordPosition">
			
	
				 <input id = "changePwd" type="text" id="fname" name="fname" placeholder="Old Password"><br>
		  <input id = "changePwd" type="text" id="fname" name="fname" placeholder="New Password"><br>
		 <input id = "changePwd" type="text" id="fname" name="fname" placeholder="Confirm New Password"><br>	</div>

		
				<div class = "submitButtons5">
			<button type="button" class="btnLast">Edit</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<button type="submit" class= "btnLast">Save</button>
	</form>	
		
	</div>
</div>
	
	
	
		{% endblock %}

ticketApp/templates/ticketApp/index.html
{% extends 'ticketApp/basic.html' %}
	{% block content %} 
	{% load static %}
	<head>

	<title>ele</title>
	

</head>
<body>
<div class = "backImage">

	<div class = "childBox">

		<div class = "cartoonPic">
			<img class = "img1" src="{% static 'ticketApp/IMAGES/cartoonPic.png'%}" alt="">
		</div>
		<div class = "socialSites">
		<ul>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/inst-icone.png'%}" alt="">instagram@insta.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/facebook-icone.png'%}" alt="">facebook@facebook.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/tiwwe-icone.png'%}" alt="">twiter@twitter.com</span></a></li>
		</ul>  
		</div>
		<div class = "linePosition">
<hr class="new4">
<div class = "dotPositionFull"><span class="dot"></span><br><p class = "h4Color">Personal details</p></div>
<div class = "dotPosition1"><span class="dot1"></span><br><p class = "h4Color">Organization details</p></div>
<div class = "dotPosition2"><span class="dot1"></span><br><p class = "h4Color">Billing address</p></div>
<div class = "dotPosition3"><span class="dot1"></span><br><p class = "h4Color">Payment method</p></div>
<div class = "dotPosition4"><span class="dot1"></span><br><p class = "h4Color">Change password</p></div>
</div>
		<div class = "personalDetailColor"><h3><b>Personal Details</h3></div>
		<div class = "personalPhoto">
	<form action = "{% url 'organizationDetails' %}" method = "GET">
	<img id="frame" src="" />
  	<div class="upload-btn-wrapper">
  	<button class="btn1">UPLOAD</button>
 	<input type="file" onchange="preview()">
	</div>
	<script src="{% static 'ticketApp/JS/script.js'%}"></script>

 
	
		</div>
<div class="drag-area">
    <div class="icon"><i class="fas fa-cloud-upload-alt"></i></div>
    <span>Drag and Drop Documents</span>
    <button>Upload</button>
    <input type="file" hidden>
  </div>
		<div class = "detailIntro">

			<div class = "labelColor"><label id = "labelFont" for="fname">Username</label>
 	 <input id = "inputShape" type="text" id="fname" name="fname" value="John"></div><br><br>
			<div class = "labelColor1"><label id = "labelFont" for="email">Email</label>
 	 <input id = "inputShape" type="email" id="email" name="email" value="email@email.com"></div><br><br>
 	 		<div class = "labelColor2"><label id = "labelFont" for="Email">Mobile</label>
 	 <input id = "inputShape" type="number" id="number1" name="number" value="8945786879"></div><br><br>
 	 		<div class = "labelColor3"><label id = "labelFont" for="email">Address 1</label>
 	 <input id = "inputShape" type="text" id="address" name="address1" value="New Delhi"></div><br><br>
 	 		<div class = "labelColor4"><label id = "labelFont" for="email">Address 2    </label>
 	 <input id = "inputShape" type="text" id="text" name="address2" value="New Delhi"></div><br><br>
 	 		<div class = "labelColor5"><label id = "labelFont" for="email">Id proof type</label>
 	 <input id = "inputShape" type="text" id="text" name="idProve" value="facscsvs"></div><br><br>
 	 		<div class = "labelColor6"><label id = "labelFont" for="email">Id number</label>
 	 <input id = "inputShape" type="text" id="idNumber" name="idNumber" value="45879 7485 2665"></div><br><br>
	

		</div>

		<div class = "submitButtons">
			<button type="button" class="btnLast">Edit</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<button type="submit" class= "btnLast">Save</button>
	</form>		
		</div>
	</div>
</div>
</body>
</html>
	{% endblock %}
	
	

ticketApp/templates/ticketApp/organizationDetails.html
{% extends 'ticketApp/basic.html' %}
	{% block content %} 
	{% load static %}
	
<div class = "backImage">
	<div class = "childBox">

		<div class = "cartoonPic">
			<img class = "img1" src="{% static 'ticketApp/IMAGES/cartoonPic.png'%}" alt="">
		</div>
		<div class = "socialSites">
		<ul>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/inst-icone.png'%}" alt="">instagram@insta.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/facebook-icone.png'%}" alt="">facebook@facebook.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/tiwwe-icone.png'%}" alt="">twiter@twitter.com</span></a></li>
		</ul>  
		</div>
		<div class = "linePosition">
<hr class="new4">
<div class = "dotPositionFull"><span class="dot"></span><br><p class = "h4Color">Personal details</p></div>
<div class = "dotPosition1"><span class="dot"></span><br><p class = "h4Color">Organization details</p></div>
<div class = "dotPosition2"><span class="dot1"></span><br><p class = "h4Color">Billing address</p></div>
<div class = "dotPosition3"><span class="dot1"></span><br><p class = "h4Color">Payment method</p></div>
<div class = "dotPosition4"><span class="dot1"></span><br><p class = "h4Color">Change password</p></div>
</div>
		<div class = "personalDetailColor"><h3><b>Organization Details</h3></div>
			
	<form action = "{% url 'billingAddress' %}" method = "GET">
	
		</div>
		<div class = "detailOrganization">

			<div class = "labelColor7"><label id = "labelFont" for="fname">Organization name</label>
 	 <input id = "inputShape" type="text" id="fname" name="fname" value="John"></div><br><br>
			
 	 		<div class = "labelColor8"><label id = "labelFont" for="Email">GSTIN</label>
 	 <input id = "inputShape" type="number" id="number1" name="number" value="8945786879"></div><br><br>
 	 		<div class = "labelColor9"><label id = "labelFont" for="email">Register address</label>
 	 <input id = "inputShape" type="text" id="address" name="address1" value="New Delhi"></div><br><br>
 	 		
 	 		<div class = "labelColor10"><label id = "labelFont" for="email">Upload gst certificate</label>
 	 <input id = "dragArea"> </div></div><br><br>

		 <div class="dragArea">
    <div class="icon"><i class="fas fa-cloud-upload-alt"></i></div>
    <span>Drag Or Drop</span>
   
    <input type="file" hidden>
  </div>


		</div>
		<div class = "submitButtons2">
			<button type="button" class="btnLast">Edit</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<button type="submit" class= "btnLast">Save</button>
	</form>		

	
	</div>	
</div>		
	
	
		{% endblock %}

ticketApp/templates/ticketApp/paymentMethods.html
{% extends 'ticketApp/basic.html' %}
	{% block content %} 
	{% load static %}
	
<div class = "backImage">
	<div class = "childBox">

		<div class = "cartoonPic">
			<img class = "img1" src="{% static 'ticketApp/IMAGES/cartoonPic.png'%}" alt="">
		</div>
		<div class = "socialSites">
		<ul>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/inst-icone.png'%}" alt="">instagram@insta.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/facebook-icone.png'%}" alt="">facebook@facebook.com</span></a></li>
			<li><a href="#"><span><img class = "socialSiteImage" src="{% static 'ticketApp/IMAGES/tiwwe-icone.png'%}" alt="">twiter@twitter.com</span></a></li>
		</ul>  
		</div>
		
		<div class = "linePosition">
<hr class="new4">
<div class = "dotPositionFull"><span class="dot"></span><br><p class = "h4Color">Personal details</p></div>
<div class = "dotPosition1"><span class="dot"></span><br><p class = "h4Color">Organization details</p></div>
<div class = "dotPosition2"><span class="dot"></span><br><p class = "h4Color">Billing address</p></div>
<div class = "dotPosition3"><span class="dot"></span><br><p class = "h4Color">Payment method</p></div>
<div class = "dotPosition4"><span class="dot1"></span><br><p class = "h4Color">Change password</p></div>
</div>
		
		<div class = "personalDetailColor"><h3><b>Payment Methods</h3></div>
				<div class = "paymentMethod">
		<ul>
			<li><a href="#"><span><img class = "paymentImage" src="{% static 'ticketApp/IMAGES/creditDebit.png'%}" alt=""><button type="button" class="btnPay">Debit Card/ Credit Card</button></span></a></li>
			<li><a href="#"><span><img class = "paymentImage" src="{% static 'ticketApp/IMAGES/gpay.jpg'%}" alt=""><button type="button" class="btnPay">Google Pay</button></span></a></li>
			<li><a href="#"><span><img class = "paymentImage" src="{% static 'ticketApp/IMAGES/paypal.png'%}" alt=""><button type="button" class="btnPay">Paypal</button></span></a></li>
		</ul>  
		</div>

	<form action = "{% url 'changePassword' %}" method = "GET">
		
		
				<div class = "submitButtons4">
			<button type="button" class="btnLast">Edit</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<button type="submit" class= "btnLast">Save</button>
	</form>	
		
	</div>
</div>
	
	
	
		{% endblock %}

ticketGenerator/templates/ticketGenerator/basic.html
<!-- Welcome Commander What's New on your Creative Mind' -->
{% load static %}
<!doctype html>

<html lang="en">
<head>
	<meta charset="utf-8">

	<meta name="description" content="The HTML5 Herald">
	<meta name="author" content="SitePoint">

	<link rel="stylesheet" href="{% static 'ticketGenerator/CSS/style.css'%}">
<!--	<link rel="stylesheet" href="{% static 'ticketGenerator/CSS/bootstrap.css'%}">-->
	<script src="{% static 'ticketGenerator/JS/script.js'%}"></script>
	   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
<!--	<script src="{% static 'ticketGenerator/JS/jquery.js'%}"></script>-->
<!--	<script src="{% static 'ticketGenerator/JS/bootstrap.js'%}"></script>-->
	<link rel = "icon" href = "{% static 'ticketGenerator/IMAGES/logo.png'%}" type = "image/x-icon">

</head>
<body>

<body>

<header>
  <nav>
    <div class="logo">
      <img class = "img1" src="{% static 'ticketGenerator/IMAGES/logo.png'%}" alt="">
    </div>
    <ul>
      <li><a href="#">E-Booking</a></li>
      <li><a href="#">About us</a></li>
      <li><a href="#">Services</a></li>
      <li><a href="#">Contact Us </a></li>
      <li><a href="#">Reviews</a></li>
      <li><a href="{% url 'index' %}">My Account</a></li>
      <li><a href="#">Join Us</a></li>
    </ul>
  </nav>
  <div class="user-detail">
    <ul>
      <li><a href="#" class="login-back">log in</a></li>
      <li><a href="#">sing Up</a></li>
    </ul>
    
  </div>



<div class="social-media-icone">
  <ul>
    <li><a href="#"><span><img src="{% static 'ticketGenerator/IMAGES/google-icone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketGenerator/IMAGES/inp-licone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketGenerator/IMAGES/inst-icone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketGenerator/IMAGES/facebook-icone.png'%}" alt=""></span></a></li>
    <li><a href="#"><span><img src="{% static 'ticketGenerator/IMAGES/tiwwe-icone.png'%}" alt=""></span></a></li>
  </ul>
  

  
</div>
	
	</header>
	
	{% block content %} {% endblock %}
</body>
</html>

ticketGenerator/templates/ticketGenerator/disputeTicket.html
<!-- Welcome Commander What's New on your Creative Mind' -->

{% extends 'ticketGenerator/basic.html' %}
	{% block content %} 
	{% load static %}
	
<div class = "tableArea">
	<h2 class = "h3Design">DISPUTE TICKET</h2>
	<div class = "tableLogo">
		<div class="topnav">
		<a class="active" href="#home">My Tickets</a>
		<a href="#news">Knowledge</a>
		<a href="#contact">Announcements</a>
		</div>
	</div>
	
	<div class = "ticketSearch">
		<input  type = "search" placeholder = "Find Tickets">
				<a href ="{% url 'ticketGenerator:generateNewTicket' %}"><button type="button" class = "buttonStart" name="name" value="kuchbhi" onclick="kuchbhi"><div class = "plusSign">+</div><div class = "tickteAdding">Add New Ticket</div></button></a>
	</div>
	<p class = "searchParagrapg">7 Tickets Total</p>

	<div class = "ticketShowOption">
	<label class="main">ALL
		<input type="checkbox">
		<span class="geekmark"></span>
	</label>
		<label class="main">ON HOLD
		<input type="checkbox">
		<span class="geekmark"></span>
	</label>
		<label class="main">IN PROGRESS
		<input type="checkbox">
		<span class="geekmark"></span>
	</label>
		<label class="main">COMPLETED
		<input type="checkbox">
		<span class="geekmark"></span>
	</label>	
	</div>
	<div class = "tableData">
		<table cellspacing="5" cellpadding="20">
			<tr>
				<th>Ticket ID</th>
				<th>Subject</th> 
				<th>Description</th>
				<th>Status</th>
				<th>Last update</th>
				<th>Support</th>
			</tr>
			<tr>
				<td>3459 </td>
				<td>Not Delivery yet</td>
				<td>Derived from Latin dolorem ipsum (“pain itself”), Lorem Ipsum</td>
				<td>ON hold</td>
				<td>May, 15,2021</td>
				<td>Yash</td>
			</tr>
			<tr>
				<td>3459 </td>
				<td>Not Delivery yet</td>
				<td>Derived from Latin dolorem ipsum (“pain itself”), Lorem Ipsum</td>
				<td>ON hold</td>
				<td>May, 15,2021</td>
				<td>Yash</td>
			</tr>
			<tr>
				<td>3459 </td>
				<td>Not Delivery yet</td>
				<td>Derived from Latin dolorem ipsum (“pain itself”), Lorem Ipsum</td>
				<td>ON hold</td>
				<td>May, 15,2021</td>
				<td>Yash</td>
			</tr>
		</table>		
	</div>
	
	
		<button type="button" class = "nextButtonDesign" value="caption" onclick="" ><a href ="{% url 'ticketGenerator:generateNewTicket' %}">Next</a></button>
		
	
</div>
	
	
		{% endblock %}

ticketGenerator/templates/ticketGenerator/generateNewTicket.html
<!-- Welcome Commander What's New on your Creative Mind' -->

{% extends 'ticketGenerator/basic.html' %}
	{% block content %} 
	{% load static %}
	
<div class = "tableArea">
	<h2 class ="generateHeading">GENERATE NEW TICKET</h2>
	<div class = "generatingLayout">
		<p class = "formHeading">Your Ticket Details</p>
		<p class = "formDiscription">Enter your ticket detail below. If you are reporting a problem, please remember to provide as much information that is relevant to the issue as possible</p>
		
		<p class = "formDiscription2">General Information</p>
				
		<div  class = "generateTable">
			<label for=“inputWidth”>Full Name</label>
			<input type = "text" class ="inputWidth"><br/><br/>
			<label for=“inputWidth1”>Email</label>
			<input type = "email" class ="inputWidth1"><br/></br>
			<label for=“inputWidth2”>Priority</label>
			<input type = "text" class ="inputWidth2">
		</div>
	
		<p class = "formDiscription3">Contact</p>
		<div  class = "generateTable1">
			<label for=“inputWidth3”>Phone</label>
			<input type = "number" class ="inputWidth3"><br/><br/>
		</div>
		
		<p class = "formDiscription4">Message Detail</p>
		<div  class = "generateTable2">
			<label for=“inputWidth4”>Subject</label>
			<input type = "text" class ="inputWidth4"><br/><br/>
		</div>
		<p class = "formDiscription5">Description</p>
		<div  class = "generateTable3">
			<label for=“inputWidth5”></label>
			<input type = "text" class ="inputWidth5">
		</div>

		</div>	
					<a href ="{% url 'ticketGenerator:todayOffer' %}"><button type="button" class = "nextButtonDesignGenerator" value="caption" onclick="" >Submit</button></a>
	</div>

	
</div>	
	
	
		{% endblock %}